# Generated by Django 2.0.5 on 2018-07-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180706_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(default='', help_text='演员照片url', max_length=400, verbose_name='演员照片url')),
                ('name', models.CharField(default='', help_text='演员名', max_length=20, verbose_name='演员名')),
                ('act', models.CharField(default='', help_text='饰演角色', max_length=20, verbose_name='饰演角色')),
                ('movieid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movies.Movies', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影主演',
                'verbose_name_plural': '电影主演',
            },
        ),
        migrations.CreateModel(
            name='Stills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(default='', help_text='剧照url', max_length=400, verbose_name='剧照url')),
                ('movieid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stills', to='movies.Movies', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影剧照',
                'verbose_name_plural': '电影剧照',
            },
        ),
    ]
