# Generated by Django 2.0.5 on 2018-07-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_actors_stills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='country',
        ),
    ]
