# Generated by Django 2.0.5 on 2018-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180706_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actor',
            field=models.CharField(default='', help_text='主演', max_length=500, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(default='', help_text='剧情简介', max_length=1000, verbose_name='剧情简介'),
        ),
    ]
