# Generated by Django 2.0.5 on 2018-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180706_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', help_text='导演', max_length=500, verbose_name='导演'),
        ),
    ]
