# Generated by Django 2.0.5 on 2018-07-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20180706_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.CharField(default='', help_text='剧情简介', max_length=1000, verbose_name='剧情简介'),
        ),
    ]
