# Generated by Django 2.0.5 on 2018-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20180706_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='act',
            field=models.CharField(default='', help_text='饰演角色', max_length=100, verbose_name='饰演角色'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='imgurl',
            field=models.CharField(default='', help_text='演员照片url', max_length=600, verbose_name='演员照片url'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='name',
            field=models.CharField(default='', help_text='演员名', max_length=100, verbose_name='演员名'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='grade',
            field=models.FloatField(default=0.0, help_text='评分', verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='stills',
            name='imgurl',
            field=models.CharField(default='', help_text='剧照url', max_length=600, verbose_name='剧照url'),
        ),
    ]
