# Generated by Django 2.0.5 on 2018-07-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20180707_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='grade',
            field=models.CharField(default='0.0', help_text='评分', max_length=5, verbose_name='评分'),
        ),
    ]
